# Generated by Django 5.1.7 on 2025-05-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_node_edge'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='custom_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
