services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      bash -c "python manage.py migrate &&
               gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --reload"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.docker
    environment:
      - DOCKER=true
      - DEBUG=False
      - ALLOWED_HOSTS=*
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16-alpine
    env_file:
      - ./backend/.env.docker
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${API_URL:-http://localhost:8000/api}
    environment:
      - REACT_APP_API_URL=${API_URL:-http://localhost:8000/api}
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: always

volumes:
  postgres_data:
